version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl
      - curl -LO "https://dl.k8s.io/release/v1.27.3/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - kubectl version --client   # 👈 DEBUG

  pre_build:
    commands:
      - echo Updating kubeconfig
      - aws eks update-kubeconfig --region us-west-2 --name devcluster

  build:
    commands:
      - echo Current directory
      - pwd
      - ls -lrt   # 👈 VERY IMPORTANT DEBUG
      - echo Deploying to EKS
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
